# Generated by Django 5.1.3 on 2024-12-10 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0005_category_contato_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
    ]
